### ISSUE TITLE
Roadmap proposal

### ISSUE THREAD

**Issue by jovanbulck** [GijsTimmers/kotnetcli#54]
I agree with the proposed [roadmap](https://github.com/GijsTimmers/kotnetcli/wiki/Future-plans-and-milestones) Good plan :+1:

Would like propose some enhancements however:
#### kotnetcli 2.0

**goal:** a pluggable, cohesive, trustworthy standalone application  -- _Trusty Tahr_ ;-)

**roadmap enhancements:**

_feature freeze:_ all new feature requests (new cli/gui/command line options; login actions; communicators; ...) should be incorporated into the road map for post 2.0 release. All open issues should be labeled according to the roadmap.
- Overal software design as a set of cohesive communicating modules, as discussed [here](https://github.com/GijsTimmers/kotnetcli/wiki/Software-design) and [here](https://github.com/GijsTimmers/kotnetcli/labels/software-design) should be completed.
- Lazy importing: running kotnetcli withouth all dependencies should work nice and fine when the not-installed-dependencies aren't used (e.g. dialog, curses, keyring, ...)
- Fail gracefully: exit with appropriate exit code and communicate the reason of failure through the communicator
- a fully working `dummy-mode` stable TravisCI testsuit
#### kotnetcli 3.0

**goal:** a smooth application, nicely integrated in the operating system  -- _Precise Pangolin_ ;-)

**roadmap enhancements:**
- Fully documented software design
- Explore ideas for alternative front-ends:
  - Android app
  - Gnome 3 / unity application indicator (http://blog.fpmurphy.com/2011/04/gnome-3-shell-extensions.html)
  - proof-of-concept dialog gui?
- Auto starting kotnetcli:
  - at boot time: robust way of telling whether or not on kotnet network
  - at network changing time: hooking up on ethernet plugin event? Wifi network change?
- Installers for various OSs:
  - AUR, deb file, windows installer, dialog based installer?
  - install to /usr/local/bin
  - auto install small man page?
- self containing builds for a variety of operating systems
- Config file `~/.kotnetcli` with user default options?

Of course @GijsTimmers decides on the roadmap, so consider this as a proposal to incorporate the software design in the roadmap. Just a personal view / things I will be working on

Comments / Impressions / Ideas?

**Comment by jovanbulck** [comment]
another idea for integration in 3.0: auto-completion support for `zsh` and `jsh` for the various cli options:

- http://stackoverflow.com/questions/10194558/auto-completion-in-zsh-on-3rd-parameter
- http://bewatermyfriend.org/p/2012/003/

**Comment by GijsTimmers** [comment]
- [x] #9: Better exception handling
- [x] #59 Verkeerde credentials moeten in de communicator, zodat ze altijd
  worden geprint en niet alleen bij een bep. `logging`-level
- [x]   : ERROR_CODES bedenken om in speciale situaties meer details weer
  te geven:
  --> communicator.beeindig_sessie --> communicator.panic()
  --> communicator.
  --> communicator.talk()
  --> communicator.panic(): heftige shit
  
  Stacktrace wordt alleen geprint bij onverwachte exceptions.
  Wordt geprint in STDOUT ná de communicator, wat die ook zijn moge.
- [x] Minder communicatorstappen:
  Netlogin openen... --> Gegevens ophalen...
  Gegevens invoeren WEG
- [ ] Migratie naar Engels als taal in code
- [x] Vanavond: features:
  - Enkel login, geen logout of forceerlogin
  - Communicators: hoogstens plaintext/colorama, rest later
  - Nu geen configuratiebestanden.
- [ ] Setuptools: pas het script aan:
  sudo ./setup.py install kotnetcli: 
  - kotnetcli
  
  sudo ./setup.py install kotnetcli --development:
  - kotnetcli
  - kotnetcli-dev
  - kotnetcli-srv
